### ISSUE TITLE
electron-store

### ISSUE THREAD

**Issue by youyfeng** [caoxiemeihao/electron-vue-vite#10]
桌面应用刷新时， new Store({ name: 'electron-vue' }) 会阻塞应用的重新载入。去除这个加载也会快很多，具体原因我没有找到

**Comment by caoxiemeihao** [comment]
你可能得这么写 😷

```diff
- new Store({ name: 'electron-vue' })
+ new Store()
```

可能 electron-store 在渲染进程用 fs 的异步 API 了
渲染进程使用 NodeJs 的异步 API 会导致很多奇奇怪怪的 BUG
去年我写过一个 C 插件，当时碰到的情况是在渲染进程中运行有问题；后来没办法搬到主进程去运行就好了 🤢

**Comment by youyfeng** [comment]
> 你可能得这么写 😷
> 
> ```diff
> - new Store({ name: 'electron-vue' })
> + new Store()
> ```
> 
> 可能 electron-store 在渲染进程用 fs 的异步 API 了
> 渲染进程使用 NodeJs 的异步 API 会导致很多奇奇怪怪的 BUG
> 去年我写过一个 C 插件，当时碰到的情况是在渲染进程中运行有问题；后来没办法搬到主进程去运行就好了 🤢

使用new Store()还是会存在一样的问题，暂时先去掉这个。有交流群吗

**Comment by caoxiemeihao** [comment]
> > 你可能得这么写 😷
> > ```diff
> > - new Store({ name: 'electron-vue' })
> > + new Store()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可能 electron-store 在渲染进程用 fs 的异步 API 了
> > 渲染进程使用 NodeJs 的异步 API 会导致很多奇奇怪怪的 BUG
> > 去年我写过一个 C 插件，当时碰到的情况是在渲染进程中运行有问题；后来没办法搬到主进程去运行就好了 🤢
> 
> 使用new Store()还是会存在一样的问题，暂时先去掉这个。有交流群吗

你建一个交流群 😂

**Comment by caoxiemeihao** [comment]
微信群已建，请看 README
