### ISSUE TITLE
router引入有问题

### ISSUE THREAD

**Issue by UMRzcz-831** [caoxiemeihao/electron-vue-vite#12]
![image](https://user-images.githubusercontent.com/52395980/122045302-24f88f00-ce10-11eb-816d-c794ad583cd7.png)

**Comment by caoxiemeihao** [comment]
看看你装的 router 版本
vue3 要用 vue-router@4.0

**Comment by caoxiemeihao** [comment]
你可以试试 master 分支，master 分支有集成 router
