### ISSUE TITLE
[Help] 当我修改template部分代码的时候，热更新经常无效

### ISSUE THREAD

**Issue by jawalkwan** [caoxiemeihao/electron-vue-vite#149]
不确定是我本地环境的问题还是框架的配置问题
我用的是vscode+volar
ide和插件的版本都是最新的
麻烦协助一下🙏

**Comment by caoxiemeihao** [comment]
新版 v2.0.0 你试试还有这个问题嘛

**Comment by delayhsiao** [comment]
> 新版 v2.0.0 你试试还有这个问题嘛

哪个的2.0啊？@caoxiemeihao

**Comment by delayhsiao** [comment]
> 新版 v2.0.0 你试试还有这个问题嘛

昂，看commit才发现到2.0了，release还在1.0😂，怎么升级呢？

**Comment by caoxiemeihao** [comment]
手动迁移下业务代码
