### ISSUE TITLE
[Bug] Can not enable Context Isolation

### ISSUE THREAD

**Issue by Saeid-Za** [caoxiemeihao/electron-vue-vite#162]
#### What did I do

~Using the template provided in this repository, I wanted to enable `contextIsolation` to seperate `Main` and `Preload` contexes.
I also, disabled the `nodeIntegration`.
Here's the code i've changed.~

False positive, I can not reproduce this problem on the provided template. 

```ts
  win = new BrowserWindow({
    title: 'Main window',
    webPreferences: {
      preload: splash,
      contextIsolation: true,
    },
  })

```
note that `nodeIntegration` is disabled by default.

#### What happened

I got this error.

```js
Uncaught ReferenceError: require is not defined
    at promises.js:2:11
```

which I assume that the `vite-plugin-electron` package is not handling this configuration and nodejs code is being leaked into browser context.

#### Expected

There should be no error when enabling `contextIsolation`.

#### Environment

- OS: Ubuntu 22
- electron-vue-vite  v2.0.0

**Comment by caoxiemeihao** [comment]
@stalkercn 没人逼着你用，我这个项目太烂，不和你胃口

**Comment by Jayczee** [comment]
@caoxiemeihao 大佬那现在这个问题还是没法解决嘛没法开启嘛？我按照官网的文档操作也报这个错

**Comment by caoxiemeihao** [comment]
> 大佬那现在这个问题还是没法解决嘛没法开启嘛？我按照官网的文档操作也报这个错
这不很简单的东西吗？你没发现是提 issue 的人自己关的 issue?
