### ISSUE TITLE
改文件，一热更新就出现 问题

### ISSUE THREAD

**Issue by Xwudao** [caoxiemeihao/electron-vue-vite#18]
![image](https://user-images.githubusercontent.com/31327868/126094005-471f0276-04ab-4fbe-803c-c31a0ba449f3.png)

首先是界面不会变，无论改什么文件。

其次，developer tools 也是全部空白

![image](https://user-images.githubusercontent.com/31327868/126094051-a6f9e332-0104-4661-97f5-b8f3f2607a12.png)

![image](https://user-images.githubusercontent.com/31327868/126094061-eaf94596-b600-4bce-a683-f72720324a2e.png)

请问是怎么回事呢

**Comment by caoxiemeihao** [comment]
代码拉下来就是这样嘛 😷

**Comment by Xwudao** [comment]
> 代码拉下来就是这样嘛 😷

https://github.com/Xwudao/vite-electron-demo

改了一部分代码，但是我觉得应该影响不大。

首次`yarn dev`没问题，但是一改Login.vue就会出现空白问题。

代码在上面

**Comment by caoxiemeihao** [comment]
> > 代码拉下来就是这样嘛 😷
> 
> https://github.com/Xwudao/vite-electron-demo
> 
> 改了一部分代码，但是我觉得应该影响不大。
> 
> 首次`yarn dev`没问题，但是一改Login.vue就会出现空白问题。
> 
> 代码在上面

页面 404 😷

**Comment by Xwudao** [comment]
> > > 代码拉下来就是这样嘛 😷
> > 
> > 
> > https://github.com/Xwudao/vite-electron-demo
> > 改了一部分代码，但是我觉得应该影响不大。
> > 首次`yarn dev`没问题，但是一改Login.vue就会出现空白问题。
> > 代码在上面
> 
> 页面 404 😷

可以了

**Comment by caoxiemeihao** [comment]
```js
setTimeout(() => {
  console.log('ipcRenderer:', ipcRenderer);
  // Configuration name causes hot updates to be slow | 传递 name 后会导致热更新很慢
  // console.log('electron-store', new Store({ name: 'electron-vue' }))
  // https://github.com/caoxiemeihao/electron-vue-vite/issues/10
  **** console.log('electron-store', new Store()); ****

  // new Store 会阻塞线程，导致 preload 动画卡顿
}, 2999);
```
这个问题是 ` new Store()`  的锅 😅
