### ISSUE TITLE
模块用import/require引入的问题

### ISSUE THREAD

**Issue by plusl894860970** [caoxiemeihao/electron-vue-vite#19]
用import会有代码提示，但是运行时会报错；用require正常，但是写代码的时候会失去代码提示。
import { chromium } from 'playwright' 运行时会报错
const { chromium } = require('playwright') 在开发的时候无代码提示
目前我的情况是这样的，十分致命，有什么好的方案吗

**Comment by caoxiemeihao** [comment]
`import { chromium } from 'playwright' ` 这个写法，打包后能跑起来么？
如果能跑起来，那就好办了！

**Comment by plusl894860970** [comment]
破案了。引用的时候依然是用require。然后ts定义类型的时候import对应的类就有提示了、、
