### ISSUE TITLE
请问我在引入 and-design 时报错

### ISSUE THREAD

**Issue by zhenjie1** [caoxiemeihao/electron-vue-vite#2]
我在使用 and-design 时控制台一直有报错,我不太清楚是哪里的问题

![image](https://user-images.githubusercontent.com/20718255/95669563-d2960d00-0bb4-11eb-9a00-14a4adbdfd91.png)

**Comment by zhenjie1** [comment]
![image](https://user-images.githubusercontent.com/20718255/95669575-eb9ebe00-0bb4-11eb-9b86-0b49bfd8c488.png)
我是这样引入的

**Comment by zhenjie1** [comment]
我是这样引入的

![image](https://user-images.githubusercontent.com/20718255/95669589-fd806100-0bb4-11eb-9439-d6a68197a490.png)

**Comment by zhenjie1** [comment]
老哥, 理我一下

**Comment by caoxiemeihao** [comment]
这个我会出一个 antdv 分支 😘

**Comment by caoxiemeihao** [comment]
> 这个我会出一个 antdv 分支 😘

已发 antdv 分支
