### ISSUE TITLE
开发运行报错

### ISSUE THREAD

**Issue by ywwsw** [caoxiemeihao/electron-vue-vite#22]
[pre] @rollup/plugin-typescript TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

这个是什么问题，但不影响使用。

微信群再发一下呗，似乎过期了

**Comment by caoxiemeihao** [comment]
> [pre] @rollup/plugin-typescript TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
> 
> 这个是什么问题，但不影响使用。
> 
> 微信群再发一下呗，似乎过期了

微信已重发 😄
这个警告是  @rollup/plugin-typescript 报出来的，礼拜天我看看 😅
