### ISSUE TITLE
electron api调用报错

### ISSUE THREAD

**Issue by bfclouds** [caoxiemeihao/electron-vue-vite#23]
-  无法正确调用electron的方法
-  ![image](https://user-images.githubusercontent.com/39664979/130176037-ce890276-234f-4213-9743-041fe74d8655.png)
-  以下调用都会报错
-   ![image](https://user-images.githubusercontent.com/39664979/130176141-ae905949-6427-47eb-8648-006c1dfe25a9.png)

**Comment by caoxiemeihao** [comment]
渲染进程无法使用主进程 API
app.whenReady 是主进程的 API
