### ISSUE TITLE
windows系统run build之后的程序，打开后报错。

### ISSUE THREAD

**Issue by 1949Lee** [caoxiemeihao/electron-vue-vite#26]
错误：Uncaught TypeError: path.join is not a function
报错的代码是electron依赖里的const pathFile = path.join(__dirname, 'path.txt');
我在vue中使用了node的原生api，是和这个有关系吗

**Comment by 1949Lee** [comment]
我重新clone了代码，没做任何修改直接build之后，也会报同样的错误

**Comment by caoxiemeihao** [comment]
> 我重新clone了代码，没做任何修改直接build之后，也会报同样的错误

你打开的是 unzip 的版本吧，用 .exe 安装文件呢

**Comment by 1949Lee** [comment]
一样

**Comment by 1949Lee** [comment]
> > 我重新clone了代码，没做任何修改直接build之后，也会报同样的错误
> 
> 你打开的是 unzip 的版本吧，用 .exe 安装文件呢

一样

**Comment by caoxiemeihao** [comment]
> 错误：Uncaught TypeError: path.join is not a function
> 报错的代码是electron依赖里的const pathFile = path.join(__dirname, 'path.txt');
> 我在vue中使用了node的原生api，是和这个有关系吗

代码贴出来看看呢；可能写法导致打包问题
```js
import * as path from 'path'

path.join() 
```
或
```js
import { join } from 'path'

join()
```
