### ISSUE TITLE
builid问题

### ISSUE THREAD

**Issue by Xqrrrr** [caoxiemeihao/electron-vue-vite#27]
使用示例，build之后，提示 [build-main.ts] Electron build...@rollup/plugin-typescript TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

**Comment by caoxiemeihao** [comment]
> 使用示例，build之后，提示 [build-main.ts] Electron build...@rollup/plugin-typescript TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

这个是⚠️，不影响使用；得空会修复他 😅
