### ISSUE TITLE
Should build.outDir use relative path?

### ISSUE THREAD

**Issue by Enoooch** [caoxiemeihao/electron-vue-vite#32]
```
build: {
      outDir: '../../dist/render',
      emptyOutDir: true,
      minify: false,
      commonjsOptions: {},
      sourcemap: true,
}
```
It's may not compatible with some plugins.
In those case ```outDir``` is relative to ```root```.

**Comment by caoxiemeihao** [comment]
You are right 👍

**Comment by caoxiemeihao** [comment]
I'm going to refactor the project, nearby two days

**Comment by caoxiemeihao** [comment]
The project has been refactor.
All config file in `configs` directory.
`outDir` use relative path.
