### ISSUE TITLE
支持多窗口

### ISSUE THREAD

**Issue by betterRunner** [caoxiemeihao/electron-vue-vite#4]
感谢作者精巧的demo~

是否有考虑支持多窗口？
我尝试创建一个新的窗口window2，`window2.loadURL()`和`window2.loadFile()`都尝过，但是不知道window2.html的文件该怎么和vite或者rollup绑定，以前基于webpack的是可以绑定多个入口的。不知道是否与目前vite的配置只支持一个入口的原因（https://github.com/vitejs/vite/issues/257有聊到）

**Comment by caoxiemeihao** [comment]
我说一个场景
第一步：打开软件进入登录 -> 第一个窗口
第二部：登录后进入主页，关闭登录窗口 -> 第二个窗口
是酱紫么

**Comment by betterRunner** [comment]
大概是这个意思，不过我这里希望是做成一个frameless的隐形窗口用来处理cpu密集型任务的

目前我暂时hack的做法是直接用rollup打包第二个窗口的代码，但是如果vite那边能统一打包两个窗口的代码是最好的

**Comment by caoxiemeihao** [comment]
> 大概是这个意思，不过我这里希望是做成一个frameless的隐形窗口用来处理cpu密集型任务的
> 
> 目前我暂时hack的做法是直接用rollup打包第二个窗口的代码，但是如果vite那边能统一打包两个窗口的代码是最好的

cpu 密集型任务，为啥不直接用 NodeJs 的 child_process :)
antd 分支里面我打算把登陆独立出来，增加下使用体验；大概五天内吧
