### ISSUE TITLE
渲染层js更改后，vite热更新触发，主进程向渲染层通讯，渲染层会打印多次信息

### ISSUE THREAD

**Issue by XSnowHoly** [caoxiemeihao/electron-vue-vite#40]
代码拉下来后，没有更改启动开发环境的相关配置。
渲染层js更改后，vite热更新触发，主进程向渲染层通讯，渲染层会打印多次信息
使用自带的菜单 View -> Reload  渲染层重新加载后信息打印恢复正常

举例，主进程只发送了一次消息给渲染层，然后在渲染层 devTools 打印了多次信息

**Comment by XSnowHoly** [comment]
![截图20211213143102](https://user-images.githubusercontent.com/25945988/145763788-225b980e-d9d0-491f-bc25-7cf44b2a06fd.png)

**Comment by XSnowHoly** [comment]
![image](https://user-images.githubusercontent.com/25945988/145763831-6e0bd9a9-2ef2-4737-ac70-ee729ebb3e28.png)

**Comment by caoxiemeihao** [comment]
你这个 renderer 打印应该会随着 hrm 更新越来越多，ipcRenderer.on 堆积了
你代码写出了副作用没处理好，和模板没关系；你排查下

**Comment by XSnowHoly** [comment]
> 你这个 renderer 打印应该会随着 hrm 更新越来越多，ipcRenderer.on 堆积了 你代码写出了副作用没处理好，和模板没关系；你排查下

感谢作者回复！ 是我问题方向找错了，的确是多次 hrm 更新后触发 mounted 调用多次重复的 ipcRenderer.on 导致。
现在的处理方法是 在 onUnmounted 组件卸载时调用 removeAllListeners 删除所有事件监听器。
