### ISSUE TITLE
请教无用文件

### ISSUE THREAD

**Issue by Qiming-Liu** [caoxiemeihao/electron-vue-vite#41]
请问下\src\renderer目录下的package.json.txt和tsconfig.json是不是无用的啊, 我把这两个文件拿出来也不影响dev和build

https://github.com/caoxiemeihao/electron-vue-vite/blob/7b32a5ff4c116131f4923e3b671de18955d5b9dd/src/renderer/package.json.txt#L1

https://github.com/caoxiemeihao/electron-vue-vite/blob/7b32a5ff4c116131f4923e3b671de18955d5b9dd/src/renderer/tsconfig.json#L1

**Comment by caoxiemeihao** [comment]
package.json.txt 是没用的
tsconfig.json 是有用的

**Comment by Qiming-Liu** [comment]
明白了, 那挺好的, 谢谢
