### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by peterkimzz** [caoxiemeihao/electron-vue-vite#43]
Hi, this is Peter.

```ts
import { shell } from 'electron' // raises `__dirname is not defined` error.

const OnPayout = () => {
  shell.openExternal('https://url.com') // not working
}
```

```ts
import electron from 'electron' // same error

const OnButton = () => {
  electron.app.quit()
}
```

This issue is raised when I import `electron` package.

2. `require` is not allowed on `vite` framework.

```ts
const OnButton = () => {
  const electron = require('electron') // `require` is not defined.
}
```

3. inline importing

```ts
const OnButton = async () => {
  const electron = await import('electron') // also `__dirname is not defined`
}
```

How can I solved it? 
Thanks!

**Comment by caoxiemeihao** [comment]
You import electron in Renderer-process?
This template is not allow use about Electron and NodeJs API. This is the limit of 'electron'.
If you want use Electron or NodeJs API in Renderer-process, you can see this npm package [vitejs-plugin-electron](https://www.npmjs.com/package/vitejs-plugin-electron) or tempalte [vite-webpack-electron](https://github.com/caoxiemeihao/vite-webpack-electron)

**Comment by caoxiemeihao** [comment]
README.md has added description. [Use Electron, NodeJs API](https://github.com/caoxiemeihao/electron-vue-vite#use-electron-nodejs-api)
