### ISSUE TITLE
dist目录没有package.js

### ISSUE THREAD

**Issue by luckyAlexandra** [caoxiemeihao/electron-vue-vite#44]
#我尝试着用configs目录来配置我原有代码的打包，但是打包出来的dist目录里没有packge.js，然后报错如下
![image](https://user-images.githubusercontent.com/6998959/147517170-95aecae8-8756-40b7-9724-48c52285fc83.png)

我找了一下这个demo项目的文件，没有找到packge.json转package.js的代码。
我的项目目录：
![image](https://user-images.githubusercontent.com/6998959/147517430-d5ded8ba-a87f-4757-b609-5776779737ca.png)
其中src相当于renderer部分的代码，sys是electron相关。
配置文件configs/vite-src.config.js
![image](https://user-images.githubusercontent.com/6998959/147517568-42d42b40-6ee0-4664-8e99-37141135e150.png)

配置文件configs/vite-sys.config.js
![image](https://user-images.githubusercontent.com/6998959/147517576-9945a877-f969-4a51-9df7-b8bd826a7bfa.png)
第一次写issue，如果没描述清楚我再补充啊

**Comment by caoxiemeihao** [comment]
打包后的目录结构其实这这样的，dist 与 package.json 本就是平级的；
打包后也是，所见即所得，你细品
![image](https://user-images.githubusercontent.com/26263658/147518132-8dfeb0d7-d019-49bb-aee3-5530b057d1d5.png)

**Comment by luckyAlexandra** [comment]
> 打包后的目录结构其实这这样的，dist 与 package.json 本就是平级的； 打包后也是，所见即所得，你细品 ![image](https://user-images.githubusercontent.com/26263658/147518132-8dfeb0d7-d019-49bb-aee3-5530b057d1d5.png)

啊，我不太明白哈，我的dist目录也是和package.json平级的，但这个错误提示不是说，它找不到dist目录里面的package.json吗，它为什么会去里面找呢？
另外我运行demo的代码的时候，dist/main目录下有个packge.js，而且这个文件应该就是package.json转化过来的，我自己打包的项目代码没有这个文件，所以我以为是这个文件的问题来着。
![image](https://user-images.githubusercontent.com/6998959/147518451-c8a5e7f1-7351-444a-a81c-7215b9990a5d.png)

**Comment by caoxiemeihao** [comment]
你这报错是截图是开发阶段的，你代码写崩了吧 = =
我的 demo 开发、打包会出这个问题嘛？
