### ISSUE TITLE
请问在你这个项目中，要如何在vue中使用serialport这个包？

### ISSUE THREAD

**Issue by Minori-ty** [caoxiemeihao/electron-vue-vite#46]
这是我用vue-cli搭建的项目，配置vue.config.js中配置插件的external，不知道你这个项目中应该如何配置？

https://github.com/Minori-ty/vue-cli-vue3-electron-serialport.git

**Comment by Minori-ty** [comment]
也就是说，要如何运行node原生模块？

**Comment by caoxiemeihao** [comment]
按理说安装包的时候需要装到 dependencies 中就可以了，剩下的模板会自动处理的

**Comment by Minori-ty** [comment]
> 按理说安装包的时候需要装到 dependencies 中就可以了，剩下的模板会自动处理的
> 
> https://github.com/caoxiemeihao/electron-vue-vite/blob/16917388d1003aa66418b810990ef0102b4f95c2/configs/vite-main.config.ts#L21

我按照你导入fs模块那样导入serialport，但是显示的是native code，请问该如何解决？这里是我的demo：https://github.com/Minori-ty/error-demo/tree/master/electron-vue-vite

不过需要python3.9环境，下载vs studio 2017 选择C++工作负载，安装node-gyp环境

**Comment by caoxiemeihao** [comment]
你是要在 Renderer 中用啊
1. electron-vue-vite 这个模板要开启在 Renderer 中使用 NodeJs
2. 安装下 [vitejs-plugin-electron](https://www.npmjs.com/package/vitejs-plugin-electron) 到项目中，配置下 serialport 的 resolve
3. 比如像这样：

```ts
export default defineConfig({
  plugins: [
    electron({
      resolve: {
        serialport: () => `const SerialPort = require('serialport');  export default SerialPort;`,
      },
    }),
  ],
})
```

**Comment by caoxiemeihao** [comment]
> 我按照你导入fs模块那样导入serialport，但是显示的是native code，请问该如何解决？
你这句话和没问一样，显示 `native code` 这很正常。
其次，C++ 模块不推荐在 Renderer 中使用，如果有异步的任务的话；Renderer 可能会出现奇奇怪怪的 BUG
因为 Renderer 只是一个`子进程`而已，C++ 中实现中可能还会有子进程，线程之类的操作；这些在`主进程`中使用更保险

**Comment by Minori-ty** [comment]
> 你是要在 Renderer 中用啊
> 
> 1. electron-vue-vite 这个模板要开启在 Renderer 中使用 NodeJs
> 2. 安装下 [vitejs-plugin-electron](https://www.npmjs.com/package/vitejs-plugin-electron) 到项目中，配置下 serialport 的 resolve
> 3. 比如像这样：
> 
> ```ts
> export default defineConfig({
>   plugins: [
>     electron({
>       resolve: {
>         serialport: () => `const SerialPort = require('serialport'); export default SerialPort;`,
>       },
>     }),
>   ],
> })
> ```

好的，感谢你的解答。但是我按照你说的，在vite-renderer.config.ts配置了vite-plugin-electron

![image](https://user-images.githubusercontent.com/79521943/148475934-4275fc68-2019-42ab-acaf-ac5d0c52ce1c.png)

然后在renderer App.vue中使用，依旧是native code

![image](https://user-images.githubusercontent.com/79521943/148476021-a7a22f15-c59b-4714-a95b-46616284ff7a.png)

**Comment by caoxiemeihao** [comment]
我用你的项目试下

**Comment by Minori-ty** [comment]
> 我用你的项目试下

感谢您的热心解答

**Comment by caoxiemeihao** [comment]
> 感谢您的热心解答

[vitejs-plugin-electron](https://www.npmjs.com/package/vitejs-plugin-electron) 这个包要升到 `1.3.0` 就支持函数式写法了
其次我才意识到我用的 `Mac` 没法用 `Visual Studio 2017` 😶
另外，在 Renderer 中已经打印出 `f SerialPort() { [native code] }` 了，岂不是可以只用了？你用它还会报什么错？

**Comment by Minori-ty** [comment]
> > 感谢您的热心解答
> 
> [vitejs-plugin-electron](https://www.npmjs.com/package/vitejs-plugin-electron) 这个包要升到 `1.3.0` 就支持函数式写法了 其次我才意识到我用的 `Mac` 没法用 `Visual Studio 2017` 😶 另外，在 Renderer 中已经打印出 `f SerialPort() { [native code] }` 了，岂不是可以使用了？你用它还会报什么错？

Visual Studio 2019也行，Mac有2019的，https://visualstudio.microsoft.com/zh-hans/downloads/
会报undefined

**Comment by caoxiemeihao** [comment]
你这个问题不是不兼容 C++ 模块的问题；人家 issues 中有明确说明在 Renderer 中使用 serialport 碰到了种种问题
https://github.com/electron/electron/issues/18397
我个人还是建议你在 Main 进程中使用 serialport；这种问题能避则避

**Comment by caoxiemeihao** [comment]
说来我几年前跑起来过一次，那时候菜的亚皮；也不知道怎么跑起来的
https://github.com/caoxiemeihao/electron-weigh

**Comment by Minori-ty** [comment]
> 你这个问题不是不兼容 C++ 模块的问题；人家 issues 中有明确说明在 Renderer 中使用 serialport 碰到了种种问题 [electron/electron#18397](https://github.com/electron/electron/issues/18397) 我个人还是建议你在 Main 进程中使用 serialport；这种问题能避则避

好的，谢谢你

**Comment by caoxiemeihao** [comment]
早上试了下，用 `electron-rebuild` 重新编译下；在 Main 进程中跑是没有问题的。

**Comment by Minori-ty** [comment]
> 早上试了下，用 `electron-rebuild` 重新编译下；在 Main 进程中跑是没有问题的。

好的谢谢你，不过我们是要跑在render的，我再去研究一下

**Comment by caoxiemeihao** [comment]
官方有提供 Demo
https://github.com/serialport/electron-serialport

**Comment by Minori-ty** [comment]
> * TODO

好的，我已经解决了这个问题了。

**Comment by Emeryao** [comment]
@Minori-ty 兄弟怎么解决的？能在render process里用了吗？

**Comment by Minori-ty** [comment]
> @Minori-ty 兄弟怎么解决的？能在render process里用了吗？

作者提供了另外一个模板了，git@github.com:caoxiemeihao/electron-vite-boilerplate.git

关键在于开启 ` nodeIntegration: true, contextIsolation: false,` 下载serialport@10.0.0，如果还是不行，还要在对应的vite.config.js里面把serialport external外部化。

**Comment by Emeryao** [comment]
@Minori-ty 用serialport@10.x好了 谢谢

**Comment by Walter3019** [comment]
@caoxiemeihao 您好 我在打包项目后 运行release下win-unpacked执行文件，报错显示找不到serialport包 只有解压asar 把serialport npm i进去 再压成asar 才可以正常使用

1. 我在package.json的依赖里添加了serialport了
2. 我在主进程里使用的
