### ISSUE TITLE
[Help] windows安装包可以支持多语言吗

### ISSUE THREAD

**Issue by wjx0912** [caoxiemeihao/electron-vue-vite#464]
安装的第一个界面是语言选择对话框，这个有办法做吗，万分感谢

**Comment by RSS1102** [comment]
可以使用 [nsis](https://nsis.sourceforge.io/Main_Page)，[electron-builder#nisi](https://www.electron.build/generated/nsisoptions)自定义安装页面. 
或者有其他方法。
