### ISSUE TITLE
Use `sqlite3`, `serialport` or other `C++` addons | 使用 `sqlite3`, `serialport` 等 `C++` 模块

### ISSUE THREAD

**Issue by caoxiemeihao** [caoxiemeihao/electron-vue-vite#47]

**Comment by Minori-ty** [comment]
什么意思？

**Comment by caoxiemeihao** [comment]
> 什么意思？

这不都上班嘛，都要打工干饭的  
这个 issues 是统一解释使用 C++ addons 的  
有空我会更新下使用方法

**Comment by Minori-ty** [comment]
> > 什么意思？
> 
> 这不都上班嘛，都要打工干饭的 这个 issues 是统一解释使用 C++ addons 的 有空我会更新下使用方法

哈哈，我的任务就是做electron，现在找解决方案找疯了

**Comment by caoxiemeihao** [comment]
> 哈哈，我的任务就是做electron，现在找解决方案找疯了

我倒是想来着，很多时候不是你的工作就是你喜欢做的事情

**Comment by hoganjobs** [comment]
关于C++ addons，如何加载自己写的.cpp文件通过node-gyp生成的.node文件？thks

**Comment by caoxiemeihao** [comment]
主进程使用还是渲染进程？已经打包了 npm 还是未打包？

**Comment by hoganjobs** [comment]
先描述一下我的操作：
1、windows系统下，安装好node-gyp，采用node-gyp对binding.gyp、hello.cpp构建出hello.node文件
2、用electron-rebuild重构hello.node文件
3、在主进程electron/main/index.ts中引入使用
```js
const addon = require('./hello.node')
```
错误提示：cannot find module './hello.node'

不知道如何才能正确加载.node文件，thks

**Comment by hoganjobs** [comment]
补充：
hello.node路径：electron/main/hello.node
上述操作都是未打包阶段，仅执行了npm run dev
另：所以也不知打包还需要如何正确导入，规避哪些操作

**Comment by caoxiemeihao** [comment]
> 补充： hello.node路径：electron/main/hello.node 上述操作都是未打包阶段，仅执行了npm run dev 另：所以也不知打包还需要如何正确导入，规避哪些操作

Main 进程目前使用的是 Vite 构建模式打包，正所谓 bundle 方案。你这里用了 require 也会被识别成引入文件，默认是不支持的。
需要将 `.node` 文件用插件 copy 到 `dist/electron/main` 相对应的路径才能 `require('./xxx.node')` 这么使用。

这两天在开发一个新插件 https://github.com/caoxiemeihao/vite-electron-plugin 能无缝支持你的需求。感兴趣可以去那边讨论。
