### ISSUE TITLE
mac打包后白屏

### ISSUE THREAD

**Issue by JmStefanAndroid** [caoxiemeihao/electron-vue-vite#48]
![image](https://user-images.githubusercontent.com/15886002/148507013-3ebd05a4-403b-4585-a8cf-ae32901aac89.png)
我用你的项目，作为框架，增加了一些python脚本的调用，使用build打包mac后，打开白屏，查看原因是找不到路径，另外我的asar也没法把生成的app.asar解压

**Comment by caoxiemeihao** [comment]
大佬，你这是安装了嘛；还是直接在 release 中双击了一波

**Comment by JmStefanAndroid** [comment]
因为我的应用名有中文

**Comment by caoxiemeihao** [comment]
顺着加载路径到文件夹里 `asar e app.asar app-asar` 然后 `open app-asar` 看看 `dist/renderer/index.html` 有没有呢

**Comment by JmStefanAndroid** [comment]
> 
![image](https://user-images.githubusercontent.com/15886002/148518131-dd610ab8-1583-40c8-b809-bd6f5db0c0ce.png)
可能是中文名的问题，我换成英文名字后，可以看到报错了，我在preload用了个python-shell，找不到了

**Comment by JmStefanAndroid** [comment]
> 顺着加载路径到文件夹里 `asar e app.asar app-asar` 然后 `open app-asar` 看看 `dist/renderer/index.html` 有没有呢
preload在打包后找不到我依赖的包

**Comment by caoxiemeihao** [comment]
> 我在preload用了个python-shell，找不到了
python-shell 需要安装到 dependencies 里面，electron-builder 会自动吧 dependencies 中的包打包到 app.asar 中

**Comment by JmStefanAndroid** [comment]
> > 我在preload用了个python-shell，找不到了
> 
> python-shell 需要安装到 dependencies 里面，electron-builder 会自动把 dependencies 中的包打包到 app.asar 中

![image](https://user-images.githubusercontent.com/15886002/148521397-c18e068a-c5de-48d9-b28a-645cf5647840.png)
之前就安装了，但我的脚本似乎也没有打进asar包里，需要配置这个对吗？extraResources？  楼主有没有出electron结合python开发的项目

**Comment by caoxiemeihao** [comment]
1. 我没写过 electron+python 的项目，但是 python-shell 只是个普通的 node.js 包；所以不会有问题
2. element-plus、stylus、stylus-loader、vue、vue-router 这些是 Renderer 中用的，放在 devDependencies 中即可，要在 dependenices 中也能用，就是打包后包体会变大
3. 装 stylus 就能支持 .styl 文件，stylus-loader 没用；那是给 webpack 用的
4. 要么 asar 你先关了 `asar: false`，然后观察下打包后 Resource/app 下都有哪些文件；按理说会有 node_modules 文件夹，并且里面包含 python-shell 以及它依赖的文件
https://github.com/caoxiemeihao/electron-vue-vite/blob/6ed7251f890cc893aa724c0789a00cfe383ca5c7/electron-builder.json#L3
5. *到这步应该能看出问题了~*
6. 给个建议：你这个 python-shell 最好在 Main 进程中执行，因为 python-shell 底层也是靠的”子进程“拉起的 python 环境；Renderer 只是个子进程，也就是说如果 python-shell 在 Renderer 中使用相当于”子进程再fork子进程“可能会有意想不到的 BUG

**Comment by caoxiemeihao** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/15886002/148518131-dd610ab8-1583-40c8-b809-bd6f5db0c0ce.png) 可能是中文名的问题，我换成英文名字后，可以看到报错了，我在preload用了个python-shell，找不到了

#### 你这问题是在 Renderer 中使用了 python-shell 

1. 把 python-shell 要加到 `configs/vite-renderer.config.ts` 的 `external` 中
2. 然后 build 的格式要改成 `cjs`

听起来有些麻烦，其实这个模板根本就不推荐你在 Renderer 中使用任何的 Electron, NodeJs API ；  
你要真的是想在 Renderer 中搞，推荐你用 [electron-vite-boilerplate](https://github.com/caoxiemeihao/electron-vite-boilerplate)  这个模板，且 Renderer 中已经配置好了我说的东西

**Comment by wind-hx** [comment]
![image](https://user-images.githubusercontent.com/17685971/148675487-d3625657-74bc-4d98-b245-fce2705cbf55.png)

@caoxiemeihao 大佬 打包后白屏 启动报错了 是我哪里没有配置吗

**Comment by wind-hx** [comment]
找到问题了 是axios-mapper这个组件库导出有问题 换了一个就好了

**Comment by caoxiemeihao** [comment]
> 找到问题了 是axios-mapper这个组件库导出有问题 换了一个就好了

秀秀秀

**Comment by wind-hx** [comment]
![image](https://user-images.githubusercontent.com/17685971/148718437-fc649581-b90f-4eaa-a47e-38404c8991f3.png)

@caoxiemeihao  大佬 遇到新问题了 打包后启动 loading页不见了 变成白屏了 白屏过后显示业务页面正常 看控制台也没有报错 就是loading页没了
npm run dev启动可以看到loading页

**Comment by caoxiemeihao** [comment]
> npm run dev启动可以看到loading页

你是不是改了 preload 里面什么东西；要啥loading，要啥自行车

**Comment by wind-hx** [comment]
![image](https://user-images.githubusercontent.com/17685971/148725054-b14cfdcf-239e-4412-a62b-187948a049f0.png)

天地良心 我没有改preload里的东西
我是用 https://github.com/caoxiemeihao/electron-vite-boilerplate 做模版来开发的

**Comment by wind-hx** [comment]
![image](https://user-images.githubusercontent.com/17685971/148725210-e275970e-ed44-494d-9d5f-9a57ab24d781.png)

一摸一样

**Comment by caoxiemeihao** [comment]
把你项目贴出来看看

**Comment by caoxiemeihao** [comment]
会不会闪的太快，一下就过去了

**Comment by JmStefanAndroid** [comment]
我的问题解决了，说下是啥原因引起的，我使用了vue-router，但history的模式必须得是hash，也就是createWebHashHistory，打包后白屏大概率是使用的其他库造成的

**Comment by caoxiemeihao** [comment]
> 我的问题解决了，说下是啥原因引起的，我使用了vue-router，但history的模式必须得是hash，也就是createWebHashHistory，打包后白屏大概率是使用的其他库造成的

😂 打包后 electron 加载走的是 file:// 协议，只能用 hash

**Comment by oyal** [comment]
> 我的问题解决了，说下是啥原因引起的，我使用了vue-router，但history的模式必须得是hash，也就是createWebHashHistory，打包后白屏大概率是使用的其他库造成的

我用 createWebHistory 打包成功了一次，能正常加载页面，后面重新打包就是白屏了，不知道为啥。开发者工具看 <div id="app"></div> 目录下是空的，必须要改成 createWebHashHistory 才行。

不清楚为啥第一次不用改路由模式就能运行。
