### ISSUE TITLE
pnpm build后进度一直不动

### ISSUE THREAD

**Issue by gyh333** [caoxiemeihao/electron-vue-vite#491]
![1715762501312](https://github.com/electron-vite/electron-vite-vue/assets/6347047/5c140c5f-2739-4b19-b680-b2913d9ff629)
pnpm dev执行后正常运行
pnpm build后一直停留在那里，请问是什么原因？
node版本：18.17.1
pnpm版本：8.15.4

**Comment by RSS1102** [comment]
打开这个：https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6
因为electron的win.zip在github上，下载的时候会卡在几k/s。

**Comment by gyh333** [comment]
> 打开这个：https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6 因为electron的win.zip在github上，下载的时候会卡在几k/s。

好的，谢谢

**Comment by ShiLongTowngrass** [comment]
@RSS1102 请问如何处理呢

**Comment by RSS1102** [comment]
> @RSS1102 请问如何处理呢

上面不是已经说了嘛？
