### ISSUE TITLE
打包得时候遇到个问题，不知道是什么原因引起的

### ISSUE THREAD

**Issue by ow4vggqi** [caoxiemeihao/electron-vue-vite#492]
#### Describe the problem you confuse
 • electron-builder  version=24.13.3 os=10.0.19045
  • loaded configuration  file=D:\Projects\electron-dhs\electron-vite-vue\electron-builder.json5
  • writing effective config  file=release\28.1.0\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=canvas@2.11.2 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas
    npm ERR! command failed
    npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
    npm ERR! Failed to execute 'D:\software3\node\node.exe D:\software3\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v29.3' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
    npm ERR! node-pre-gyp info using node@20.13.1 | win32 | x64
    npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v29.3-win32-unknown-x64.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v29.3-win32-unknown-x64.tar.gz
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and electron@29.3.3 (electron-v29.3 ABI, unknown) (falling back to source compile with node-gyp)
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v29.3-win32-unknown-x64.tar.gz
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@10.1.0
    npm ERR! gyp info using node@20.13.1 | win32 | x64
    npm ERR! gyp info ok
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@10.1.0
    npm ERR! gyp info using node@20.13.1 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.8.0 found at "C:\Users\LKY\AppData\Local\Programs\Python\Python38\python.exe"
    npm ERR! gyp ERR! find VS
    npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
    npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
    npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
    npm ERR! gyp ERR! find VS
    npm ERR! gyp ERR! find VS Failure details: undefined
    npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
    npm ERR! gyp ERR! find VS
    npm ERR! gyp ERR! find VS Failure details: undefined
    npm ERR! gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
    npm ERR! gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
    npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
    npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
    npm ERR! gyp ERR! find VS
    npm ERR! gyp ERR! find VS **************************************************************
    npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
    npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
    npm ERR! gyp ERR! find VS For more information consult the documentation at:
    npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
    npm ERR! gyp ERR! find VS **************************************************************
    npm ERR! gyp ERR! find VS
    npm ERR! gyp ERR! configure error
    npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
    npm ERR! gyp ERR! stack at VisualStudioFinder.fail (D:\software3\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:116:11)
    npm ERR! gyp ERR! stack at VisualStudioFinder.findVisualStudio (D:\software3\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:72:17)
    npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    npm ERR! gyp ERR! stack at async createBuildDir (D:\software3\node\node_modules\npm\node_modules\node-gyp\lib\configure.js:95:26)
    npm ERR! gyp ERR! stack at async run (D:\software3\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
    npm ERR! gyp ERR! System Windows_NT 10.0.19045
    npm ERR! gyp ERR! command "D:\\software3\\node\\node.exe" "D:\\software3\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=D:\\Projects\\electron-dhs\\electron-vite-vue\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\Projects\\electron-dhs\\electron-vite-vue\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v29.3"
    npm ERR! gyp ERR! cwd D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas
    npm ERR! gyp ERR! node -v v20.13.1
    npm ERR! gyp ERR! node-gyp -v v10.1.0
    npm ERR! gyp ERR! not ok
    npm ERR! node-pre-gyp ERR! build error
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'D:\software3\node\node.exe D:\software3\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v29.3' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Projects\electron-dhs\electron-vite-vue\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
    npm ERR! node-pre-gyp ERR! command "D:\\software3\\node\\node.exe" "D:\\Projects\\electron-dhs\\electron-vite-vue\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
    npm ERR! node-pre-gyp ERR! cwd D:\Projects\electron-dhs\electron-vite-vue\node_modules\canvas
    npm ERR! node-pre-gyp ERR! node -v v20.13.1
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
    npm ERR! node-pre-gyp ERR! not ok

    npm ERR! A complete log of this run can be found in: C:\Users\LKY\AppData\Local\npm-cache\_logs\2024-05-16T02_46_24_900Z-debug-0.log

                    command='D:\software3\node\node.exe' 'D:\software3\node\node_modules\npm\bin\npm-cli.js' rebuild canvas@2.11.2
                    workingDir=

**Comment by RSS1102** [comment]
看着好像缺少依赖：（装 Visual C++ 构建环境）https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-windows

**Comment by ow4vggqi** [comment]
问题已经解决了，是因为引入了一个canvas依赖，这个依赖需要编译才能使用，把这个依赖放到dependencies中会出问题，放到devDependencies中就好了，谢谢大佬
