### ISSUE TITLE
如何更改icon呢 无论我如何修改都不生效

### ISSUE THREAD

**Issue by howToLearnVue** [caoxiemeihao/electron-vue-vite#499]
![1719565745865](https://github.com/electron-vite/electron-vite-vue/assets/134665735/efe7edaa-e716-4a5f-ba17-1e64fd26077d)

**Comment by RSS1102** [comment]
查看build 文件夹下的文件`icon.ico`

**Comment by speauty** [comment]
main.js中的new BrowserWindow()，有个icon属性，设置一下就行了
