### ISSUE TITLE
[help]！打包报错

### ISSUE THREAD

**Issue by Xiaohua-sky** [caoxiemeihao/electron-vue-vite#504]
C:\Server\nodejs\npm.cmd run build

> electron-vue-vite@28.1.0 build
> vue-tsc --noEmit && vite build && electron-builder

vite v5.3.5 building for production...
✓ 21 modules transformed.
dist/index.html                  0.57 kB │ gzip:  0.36 kB
dist/assets/index-swksSsxw.css   1.46 kB │ gzip:  0.72 kB
dist/assets/index-D1Tg2vJu.js   61.72 kB │ gzip: 24.88 kB
✓ built in 500ms
vite v5.3.5 building for production...
✓ 1 modules transformed.
dist-electron/main/index.js  2.25 kB │ gzip: 1.11 kB
✓ built in 16ms
vite v5.3.5 building for production...
✓ 1 modules transformed.
dist-electron/preload/index.mjs  1.91 kB │ gzip: 0.88 kB
✓ built in 13ms
  • electron-builder  version=24.13.3 os=10.0.22631
  • loaded configuration  file=D:\Showdoc\electron-vite-vue-main\electron-builder.json5
  • writing effective config  file=release\28.1.0\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=29.4.5 appOutDir=release\28.1.0\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3.632s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue-main\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\943407155'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 3 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3.284s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue-main\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\947124423'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 2 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3.322s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue-main\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\990992127'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 1 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=2.801s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue-main\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\459841051'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 0 more times

进程已结束，退出代码为 1

**Comment by RSS1102** [comment]
尝试这个呢https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6

**Comment by Xiaohua-sky** [comment]
试过了，还是一样报错

> 尝试这个呢https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6

**Comment by Xiaohua-sky** [comment]
我是按下面的执行的
能运行，但是不能打包
#### clone the project
git clone https://github.com/electron-vite/electron-vite-vue.git

#### enter the project directory
cd electron-vite-vue

#### install dependency
npm install

#### develop
npm run dev

**Comment by RSS1102** [comment]
> 我是按下面的执行的 能运行，但是不能打包
> 
> #### clone the project
> git clone https://github.com/electron-vite/electron-vite-vue.git
> 
> #### enter the project directory
> cd electron-vite-vue
> 
> #### install dependency
> npm install
> 
> #### develop
> npm run dev
1. 尝试把这个打开https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6
2. 尝试使用全局梯子
![image](https://github.com/user-attachments/assets/c454348e-3c54-4d61-8291-883b5512e8ca)

**Comment by Xiaohua-sky** [comment]
> > 我是按下面的执行的 能运行，但是不能打包
> > #### clone the project
> > git clone https://github.com/electron-vite/electron-vite-vue.git
> > #### enter the project directory
> > cd electron-vite-vue
> > #### install dependency
> > npm install
> > #### develop
> > npm run dev
> 
> 1. 尝试把这个打开https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6
> 2. 尝试使用全局梯子
>    ![image](https://private-user-images.githubusercontent.com/81673017/353687962-c454348e-3c54-4d61-8291-883b5512e8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDQ3ODYsIm5iZiI6MTcyMjQwNDQ4NiwicGF0aCI6Ii84MTY3MzAxNy8zNTM2ODc5NjItYzQ1NDM0OGUtM2M1NC00ZDYxLTgyOTEtODgzYjU1MTJlOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA1NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDMzZWFiN2VjNDhkMmZmOGFiOGFhZWJiNDM4ZmRkMDNlNjIwMzFjN2M2YjdiMmY2MjM2YzY1ZTUwMWEyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XAIa26hSm_3nLuQ_Jld6SdYZ2ppO1416IrhpHgN6gM4)

第一个我重新尝试了一下，新建了一个文件夹重新git clone，然后运行build，虽然还是报错，但是有打包出来
第二个意思没懂🥺
![d55f264a3357e31bb04b9f3415d9a41](https://github.com/user-attachments/assets/8da5cb26-c298-4a3c-bae6-da5bc5f9de83)

![b9d03e432747f9de8b8b478aaca169c](https://github.com/user-attachments/assets/2dcd5d72-1c75-476b-bb75-e409ae06e9b7)

报错
C:\Server\nodejs\npm.cmd run build

> electron-vue-vite@28.1.0 build
> vue-tsc --noEmit && vite build && electron-builder

vite v5.3.5 building for production...
✓ 21 modules transformed.
dist/index.html                  0.58 kB │ gzip:  0.37 kB
dist/assets/index-Bn5L-Jkt.css   1.46 kB │ gzip:  0.72 kB
dist/assets/index-BDrAXWrC.js   61.72 kB │ gzip: 24.88 kB
✓ built in 778ms
vite v5.3.5 building for production...
✓ 1 modules transformed.
dist-electron/main/index.js  2.25 kB │ gzip: 1.11 kB
✓ built in 25ms
vite v5.3.5 building for production...
✓ 1 modules transformed.
dist-electron/preload/index.mjs  1.91 kB │ gzip: 0.88 kB
✓ built in 13ms
  • electron-builder  version=24.13.3 os=10.0.22631
  • loaded configuration  file=D:\Showdoc\electron-vite-vue\electron-builder.json5
  • writing effective config  file=release\28.1.0\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=29.4.5 appOutDir=release\28.1.0\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3m37.47s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2


    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\015053023'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 3 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=2m50.284s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2


    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\319118571'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 2 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3.977s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2


    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\895215967'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 1 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=3.983s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679.7z
    --
    Path = C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2


    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679\darwin\10.12\lib\libssl.dylib

                    command='D:\Showdoc\electron-vite-vue\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679.7z' '-oC:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign\481619679'
                    workingDir=C:\Users\F001\AppData\Local\electron-builder\Cache\winCodeSign
  • Above command failed, retrying 0 more times

进程已结束，退出代码为 1

**Comment by RSS1102** [comment]
![image](https://github.com/user-attachments/assets/fd74ecb8-99ff-478f-9af8-618d27fe926d)
百度一下这个文件，可以shou手动下载放在c盘下的某个目录下，

**Comment by SOYOJOE** [comment]
我和你一样的问题，用管理运行cmd，执行打包指令就能生成了

**Comment by Xiaohua-sky** [comment]
> ![image](https://private-user-images.githubusercontent.com/81673017/353773877-fd74ecb8-99ff-478f-9af8-618d27fe926d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzQ1NDMsIm5iZiI6MTcyMjQ3NDI0MywicGF0aCI6Ii84MTY3MzAxNy8zNTM3NzM4NzctZmQ3NGVjYjgtOTlmZi00NzhmLTlhZjgtNjE4ZDI3ZmU5MjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxMDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNTY1NmY4NTJiMzA1NTYxNDU2ZWQ0MWI5NzM2YmM5ZGYzMWJjOWU0M2U1YzVkZTU0YWUyNzhlZWRiODEyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._QUZrQ7ASV1r8fucOMQBUrdmfMWWs5iU9naQRCDRCgU) 百度一下这个文件，可以shou手动下载放在c盘下的某个目录下，
OK了，感谢感谢🌹🌹🌹
