### ISSUE TITLE
打包成windows安装包一直报错，这个应该怎么解决

### ISSUE THREAD

**Issue by sunlight-lg** [caoxiemeihao/electron-vue-vite#506]
![image](https://github.com/user-attachments/assets/9411175c-330c-4929-bfc9-d4bfb90c5da3)
![image](https://github.com/user-attachments/assets/ee7bc01b-cd30-4f5a-8d19-cd6fbbe094d0)

bu不管是怎么修改和更换镜像地址一直还是这个错误无法解决，麻烦帮忙看看这个怎么解决

**Comment by oceanlvr** [comment]
我不认为这个是一个 bug，请检查你的网络设置
