### ISSUE TITLE
[Help] 静态的js包应该怎么存放到dist-electron

### ISSUE THREAD

**Issue by QC2168** [caoxiemeihao/electron-vue-vite#510]
#### Describe the problem you confuse

必须在`vite-plugin-electron/simple`中进行处理才能在`dist-electron`文件夹中吗

我需求是，`dev`/`build`的时候，把我的js文件夹放到`dist-electron`里，这个js是一个第三方包

**Comment by QC2168** [comment]
配置了`copyPublicDir`无效

**Comment by RSS1102** [comment]
你可以尝试放在public中呢？

**Comment by QC2168** [comment]
已解决了，是放到public了里

**Comment by QC2168** [comment]
但好像一个窗口多个preload，不能通讯？
