### ISSUE TITLE
[Help] 在VS Code内启动调试时提示找不到Node.js二进制文件

### ISSUE THREAD

**Issue by wildtang** [caoxiemeihao/electron-vue-vite#515]
#### Describe the problem you confuse
在VS Code内启动调试时提示找不到Node.js二进制文件。但无论我的PowerShell，还是Cmd，启动时都已设置了自动运行fnm路径设置，请给看看如何解决哈，谢谢。

![图片](https://github.com/user-attachments/assets/74e82cc1-3cf9-46a1-b1cb-eae051585a49)
![图片](https://github.com/user-attachments/assets/c62cdd07-d437-4b40-9a38-c70e559ae974)

OS是Win 10，fnm使用scoop安装。

**Comment by paprika135** [comment]
同样的问题

**Comment by wildtang** [comment]
从fnm 切换到 nvm-windows，这个问题就解决了。
