### ISSUE TITLE
依赖好像有点问题，build报错

### ISSUE THREAD

**Issue by Yolo-00** [caoxiemeihao/electron-vue-vite#518]
PS E:\> git clone https://github.com/electron-vite/electron-vite-vue.git
Cloning into 'electron-vite-vue'...
remote: Enumerating objects: 2966, done.
remote: Counting objects: 100% (444/444), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 2966 (delta 365), reused 312 (delta 312), pack-reused 2522 (from 1)
Receiving objects: 100% (2966/2966), 15.05 MiB | 14.98 MiB/s, done.
Resolving deltas: 100% (1617/1617), done.
PS E:\> cd electron-vite-vue
PS E:\electron-vite-vue> npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 351 packages in 6s

52 packages are looking for funding
  run `npm fund` for details
PS E:\electron-vite-vue> npm run dev

> electron-vue-vite@28.1.0 dev
> vite

Port 5173 is in use, trying another one...
vite v5.4.11 building for development...

watching for file changes...
vite v5.4.11 building for development...

watching for file changes...

  VITE v5.4.11  ready in 436 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

build started...

build started... (x2)
✓ 1 modules transformed.
✓ 1 modules transformed. (x2)
dist-electron/preload/index.mjs  10.41 kB │ gzip: 4.45 kB │ map: 5.63 kB
built in 67ms.
dist-electron/main/index.js  2.86 kB │ gzip: 1.20 kB │ map: 5.62 kB
built in 70ms.

[26844:1126/185131.042:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
����: û���ҵ���� "26844"��
PS E:\electron-vite-vue> npm run build

> electron-vue-vite@28.1.0 build
> vue-tsc --noEmit && vite build && electron-builder

E:\electron-vite-vue\node_modules\vue-tsc\index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.16.0
PS E:\electron-vite-vue>

**Comment by MarkTang3611** [comment]
我用其他脚手架也是报了这个错，奇怪了

**Comment by AsakiRain** [comment]
这个问题来自 vite 和 typescript 上游，可以尝试参照下面的 comment 限制 typescript 版本来解决
https://github.com/vuejs/language-tools/issues/4484#issuecomment-2503396325
