### ISSUE TITLE
能否加上 vue-router

### ISSUE THREAD

**Issue by byoungd** [caoxiemeihao/electron-vue-vite#53]
如果可以的话，非常感谢！

**Comment by caoxiemeihao** [comment]
独立分支

**Comment by byoungd** [comment]
> TODO: branch -> vue-router

So `pinia` should be on road map too!

**Comment by caoxiemeihao** [comment]
> 

老师，我英语不行啊 🥺
`pinia` 是个不错的选择，下礼拜我抽时间开个分支

**Comment by caoxiemeihao** [comment]
feature 分支集成 `pinia` `vue-router`
https://github.com/caoxiemeihao/electron-vue-vite/tree/feature
