### ISSUE TITLE
Can't it use with vuetify?

### ISSUE THREAD

**Issue by JackuXL** [caoxiemeihao/electron-vue-vite#55]
When I run "vue add vuetify” and choose "Vite-Preview", the cli says that it cannot find the file "/public/index.html".

**Comment by caoxiemeihao** [comment]
May need to specify the "root" path？

**Comment by JackuXL** [comment]
> May need to specify the "root" path？

Thanks for answering. But I don't know how to do it. Should I configure it in " package.json"?

**Comment by JackuXL** [comment]
I trid creating `vue.config.js` file and adding `publicPath: './'` to it, but I got the same error.
![Snipaste_2022-02-03_09-46-47](https://user-images.githubusercontent.com/58510349/152267785-7598924c-d015-4b43-8369-9bed77e02ff3.png)

**Comment by caoxiemeihao** [comment]
`vue add vuetify` only worked on @vue/cli ?  
This template without cli kit management.  
you can try manual integrate vuetify, Should be easy to arrange the.
