### ISSUE TITLE
可以单步调试吗。谢谢

### ISSUE THREAD

**Issue by wjx0912** [caoxiemeihao/electron-vue-vite#56]
能不能发一个 .vscode/launch.json 呢

另外大家都是怎么调试的，还是只能打log方式？

谢谢

**Comment by caoxiemeihao** [comment]
目前主进程都是通过  log 的方式调试的
`.vscode/launch.json` 规划中；如果可以，希望参与 😄

**Comment by oceanlvr** [comment]
我可以研究下这个QAQ

**Comment by oceanlvr** [comment]
@wjx0912 看下这个 PR 能满足你的调试需求吗，还没支持 preload / worker 的调试。

https://github.com/caoxiemeihao/electron-vue-vite/pull/57

**Comment by wjx0912** [comment]
@oceanlvr
这个很好了，谢谢
