### ISSUE TITLE
DevTools failed to load source map

### ISSUE THREAD

**Issue by Matrix53** [caoxiemeihao/electron-vue-vite#61]
When running `npm run dev`, this warning occurs:
<img width="207" alt="微信图片_20220214194429" src="https://user-images.githubusercontent.com/55696968/153858489-53829d09-93db-4feb-a6f5-81c115572a85.png">
It seems the line below cause this warning, because the warning disappears after commenting this line.
https://github.com/caoxiemeihao/electron-vue-vite/blob/b9afc0fdfc0f441e3ce905f9e6a1f29f7823b956/packages/preload/vite.config.ts#L14
And I also notice this line was added in a [recent commit](https://github.com/caoxiemeihao/electron-vue-vite/commit/9c902494a105273b6185665563c3829c1f0b3bae).

**Comment by oceanlvr** [comment]
看样子是sourcemap文件路径命中不正确。可以查下路径问题

**Comment by caoxiemeihao** [comment]
🚧 When  we use a separately sourcemap file, Electron will use http+filename path.  
This causes a sourcemap load error.  
e.g: `http://127.0.0.1:3344/Users/atom/Desktop/github/electron-vue-vite/dist/preload/index.cjs.map`.  

We can set sourcemap's value of 'inline' to solve this problem.
https://github.com/caoxiemeihao/electron-vue-vite/blob/862523fdbf95d0d168c09440983552f5fbf32b3e/packages/preload/vite.config.ts#L16

**Comment by Matrix53** [comment]
Thank you for your fixes and answer! 😋
