### ISSUE TITLE
请教下如何使用electron原生的dialog API？

### ISSUE THREAD

**Issue by esolk** [caoxiemeihao/electron-vue-vite#66]
已经参照Readme的说明，对packages/preload/index.ts与packages/renderer/src/global.d.ts进行了修改

**packages/preload/index.ts**

```typescript
import { contextBridge, ipcRenderer, dialog } from 'electron';
...
contextBridge.exposeInMainWorld('dialog', dialog);
```

**packages/renderer/src/global.d.ts**

```typescript
  interface Window {
    // Expose some Api through preload script
    fs: typeof import('fs');
    ipcRenderer: import('electron').IpcRenderer;
    dialog: import('electron').Dialog;
  }
```

然后在main.ts中console.log('dialog',window.dialog) 时，输出的是undefined

测试了Electron的其他Main Process API，比如Shell，clipboard等是没问题的。唯独这个dialog不行，这是为啥捏？

**Comment by caoxiemeihao** [comment]
这中问题多看文档
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/26263658/156161407-4ffb32a1-b709-4d7b-a16b-cee7caf6c6b2.png">
