### ISSUE TITLE
[Help] 请问一下  在build main之后 我想对主进程代码进行一些处理

### ISSUE THREAD

**Issue by jiumengs** [caoxiemeihao/electron-vue-vite#74]
#### Describe the problem you Confuse
在build main之后 我想对主进程代码进行一些处理
我怎么才能使用electron中绑定的node 进行呢 其实我想对主进程代码进行一次字节码转换 
如果使用本机安装的node进行转换的话。因为electron绑定的node版本和我本机的版本并不同 所以会导致启动失败

#### More detail (optional)
<img width="807" alt="image" src="https://user-images.githubusercontent.com/39983417/158089583-c7085036-78b2-48b3-a313-d27fc571f3e0.png">

**Comment by shaohan0228** [comment]
使用nvm切换版本可行不，编译之前就切成对应的版本

**Comment by jiumengs** [comment]
> 

可行性比较小 因为并不能保证我切换的是和electron绑定的版本完全一致。并且也不是相同构建出来的node。大概率也会失败

**Comment by shaohan0228** [comment]
electron版本不是受控的么？

**Comment by jiumengs** [comment]
做过尝试。版本号是一致的 但是也不能用

**Comment by shaohan0228** [comment]
https://jishuin.proginn.com/p/763bfbd6125d 这篇文章的路子可行不

**Comment by jiumengs** [comment]
我想到的最好的方案 就是打包的时候 用node_modules的electron中的node 直接运行我写的转换脚本

**Comment by jiumengs** [comment]
> https://jishuin.proginn.com/p/763bfbd6125d 这篇文章的路子可行不

三克油 我看下
