### ISSUE TITLE
@rollup/plugin-json 这个插件引入解决什么问题？

### ISSUE THREAD

**Issue by hefangxuan** [caoxiemeihao/electron-vue-vite#8]
- `21-02-19` 报错 `https://github.com/ajv-validator/ajv/issues/1399`
  ```bash
  Circular dependency: node_modules\conf\node_modules\ajv\dist\compile\validate\dataType.js -> node_modules\conf\node_modules\ajv\dist\compile\util.js -> node_modules\conf\node_modules\ajv\dist\compile\validate\index.js -> node_modules\conf\node_modules\ajv\dist\compile\validate\dataType.js
  ```

此错误是什么问题，我去掉 @rollup/plugin-json 这个插件，就一切正常。我不是很懂，能帮我解惑吗

**Comment by caoxiemeihao** [comment]
这个报错应该不影响打包的；控制台会有警告
官方也没回答这个问题，应该会在下个版本解决这个问题；或者我们换个版本避开这个问题问题
https://github.com/ajv-validator/ajv/issues/1399

此外这个礼拜在面试，面试完了我再搞搞这个工程

**Comment by caoxiemeihao** [comment]
> 这个报错应该不影响打包的；控制台会有警告
> 官方也没回答这个问题，应该会在下个版本解决这个问题；或者我们换个版本避开这个问题
> [ajv-validator/ajv#1399](https://github.com/ajv-validator/ajv/issues/1399)
> 
> 此外这个礼拜在面试，面试完了我再搞搞这个工程

- 这个错误在 webpack 下并不会报出来；应该说 webpack 自动处理了这种情况
- 可以看看我另一个 webpack 打包的项目
- 在 rollup 下可以通过屏蔽警告⚠️解决该问题 https://github.com/rollup/rollup/issues/1089#issuecomment-365395213
- 代码已经更新，可以拉下新代码试试咯 😉
